# render.yaml

services:
  - type: web
    name: django-web-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: CLOUDINARY_CLOUD_NAME
        value: YOUR_CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        value: YOUR_CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        value: YOUR_CLOUDINARY_API_SECRET
      # Add DATABASE_URL or other necessary variables here
