# render.yaml

services:
  - type: web
    name: django-web-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bookdsearch.wsgi:application"
    envVars:
      - key: SECRET_KEY
        #  value: SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: CLOUD_NAME
        #  value: CLOUD_NAME
      - key: API_KEY
        #  value: API_KEY
      - key: API_SECRET
      #   value: API_SECRET
      # Add DATABASE_URL or other necessary variables here
